@echo off
echo Starting TALEWEAVERS Services...

echo Starting Lore Vault (Port 8001)...
start "Lore Vault" cmd /c "cd saga_lore_module && python -m uvicorn main:app --port 8001 --reload"

echo Starting World Architect API (Port 8002)...
start "World Architect" cmd /c "cd saga_architect && python -m uvicorn main:app --port 8002 --reload"

echo Starting Character Engine (Port 8003)...
start "Character Engine" cmd /c "cd saga_character_engine && python -m uvicorn main:app --port 8003 --reload"

echo Starting Encounter Engine (Port 8004)...
start "Encounter Engine" cmd /c "cd saga_encounter_engine && python -m uvicorn main:app --port 8004 --reload"

echo Starting Item Foundry (Port 8005)...
start "Item Foundry" cmd /c "cd saga_item_engine && python -m uvicorn main:app --port 8005 --reload"

echo Starting Skill Engine (Port 8006)...
start "Skill Engine" cmd /c "cd saga_skill_engine && python -m uvicorn main:app --port 8006 --reload"

echo Starting Clash Engine (Port 8007)...
start "Clash Engine" cmd /c "cd saga_clash_engine && python -m uvicorn main:app --port 8007 --reload"

echo Starting Core Game Master (Port 8000)...
start "Game Master Director" cmd /c "cd saga_gamemaster && python -m uvicorn main:app --port 8000 --reload"

echo Starting Campaign Weaver (Port 8010)...
start "Campaign Weaver" cmd /c "cd saga_campaign_weaver && python -m uvicorn main:app --port 8010 --reload"

echo Starting VTT Client (Frontend)...
start "VTT Client" cmd /c "cd saga_vtt_client && npm install && npm run dev"

echo All services are launching in separate windows!
echo Once running, navigate to the frontend URL provided by the VTT Client terminal (usually http://localhost:5173).
pause
