import json
import os
import httpx
from typing import List, Optional
from core.schemas import CampaignRoadmap, QuestNode
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv

load_dotenv()

LORE_URL = os.getenv("LORE_MODULE_URL", "http://localhost:8001")

async def fetch_world_data(world_id: str) -> dict:
    # In a real scenario, this would load from a database or file system
    # generated by Module 2. For now, we look for a local JSON or provide a mock.
    file_path = f"./data/worlds/{world_id}/Master_World.json"
    if os.path.exists(file_path):
        with open(file_path, "r") as f:
            return json.load(f)
    
    # Mock fallback
    return {
        "world_name": "Shatterlands",
        "regions": [
            {"name": "Frostbite Tundra", "factions": ["Northern Horde", "Wolf Cult"]},
            {"name": "Aether Peaks", "factions": ["Sky Merchants"]}
        ],
        "starting_area": "Frostbite Tundra"
    }

async def search_lore(query: str) -> str:
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(f"{LORE_URL}/api/lore/search", json={"query": query, "top_k": 3})
            if response.status_code == 200:
                results = response.json()
                return "\n".join([r['content'] for r in results])
    except Exception:
        pass
    return "No lore found for this context."

async def generate_roadmap(world_id: str, starting_hex: str, theme: Optional[str] = None) -> CampaignRoadmap:
    # 1. Gather Context
    world_data = await fetch_world_data(world_id)
    lore_context = await search_lore(f"factions in {world_data.get('starting_area')}")
    
    # 2. Setup LLM
    llm = ChatOpenAI(model="gpt-4o", temperature=0.7)
    structured_llm = llm.with_structured_output(CampaignRoadmap)
    
    # 3. Create Prompt
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are the T.A.L.E.W.E.A.V.E.R. Campaign Weaver. "
                   "Your job is to generate a structured 5-step quest roadmap based on world data and lore. "
                   "You MUST output raw JSON following the exact schema provided."),
        ("user", "World Context: {world_context}\nLore Context: {lore_context}\nTheme: {theme}\nStarting Hex: {hex}\n"
                 "Generate a multi-step campaign that feels cohesive and integrates these elements.")
    ])
    
    chain = prompt | structured_llm
    
    roadmap = await chain.ainvoke({
        "world_context": json.dumps(world_data),
        "lore_context": lore_context,
        "theme": theme or "Classic Fantasy",
        "hex": starting_hex
    })
    
    return roadmap

async def generate_mini_quest(seed: str, location: str) -> QuestNode:
    llm = ChatOpenAI(model="gpt-4o", temperature=0.7)
    structured_llm = llm.with_structured_output(QuestNode)
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are the T.A.L.E.W.E.A.V.E.R. Campaign Weaver. "
                   "Generate a single, self-contained mini-quest step based on the provided seed and location."),
        ("user", "Seed: {seed}\nLocation: {location}")
    ])
    
    chain = prompt | structured_llm
    
    quest = await chain.ainvoke({
        "seed": seed,
        "location": location
    })
    
    return quest
